version: '3.9'

services:
  server:
    build: ./server
    ports:
      - "5500:5500"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - db

  client:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount custom nginx.conf

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: space_console
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

volumes:
  mysql_data:
