version: '3.9'
  # FastAPI Backend Server

services:
  fastapi:
    build: ./rest-server
    ports:
      - "8000:8000"  # Exposing FastAPI app on port 8000
    environment:
      - DATABASE_URL=mymysql+pymysql://root:admin@db:3306/space_console  # Modify this to your database connection string
    volumes:
      - ./rest-server:/app
    depends_on:
      - db
    networks:
      - app_network

  # Node.js Backend Server
  server:
    build: ./server
    ports:
      - "5500:5500"
    env_file:
      - ./server/.env
    volumes:
      - ./server:/app
    depends_on:
      - db
    networks:
      - app_network

  # React Frontend Client with Nginx
  client:
    build: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/app
      - ./client/nginx.conf:/etc/nginx/conf.d/default.conf  # Mount custom nginx.conf
    networks:
      - app_network

  # MySQL Database
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: space_console
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./server/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    networks:
      - app_network

# Define custom volume to persist MySQL data
volumes:
  mysql_data:/var/lib/mysql

# Define custom network for communication between all containers
networks:
  app_network:
    driver: bridge